# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6053f14d5bd1e4f828c5ceed65797a838133953a99b28c29b5d0d5cac333435fe6f14435b4f9d0f6d0b402633295141d1a00ed6cb49ff951bf8103cc4624b05

test:
  secret_key_base: 596d961a6486fea39ac25215afc422bd2d03c82d19dae56e067818b4bc47259244997f32c8d77e0b2dafe967a7327f2e31e5518c473e3ff4500bb0d19e686028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
